Getting Started with Progressive Web Apps
guru-ce/cfp pull request #2
Opened 2017-01-23 14:51 UTC by vitormalencar

Getting Started with Progressive Web Apps  #1

2017-01-23 14:52 UTC, vitormalencar commented
Não tenho permissão para colocar as labels

2017-01-23 17:11 UTC, filipebarcos requested changes
Está faltando, na descrição do PR o link para o documento renderizado

https://github.com/vitormalencar/cfp/blob/b0ad1142cf41cff84c29c7b298e30f2a3a0766c3/palestras/evento_21/vitormalencar-Getting-Started-with-Progressive-Web-Apps.md

2017-01-23 17:11 UTC, filipebarcos commented on palestras/evento_21/vitormalencar-Getting-Started-with-Progressive-Web-Apps.md
> +Desenvolvedor FrontEnd, com foco em tecnologias novas e escaláveis, graduando em sistemas de informações, Co-fundador do DEV I/O FOR , Organizer do Google developer groups eFrontIn Fortaleza, e claro
> Organizer do Google developer groups eFrontIn Fortaleza

1. Se possível, mudar de Organizer para Organizador, já que está tudo em português 😄 
2. Faltando um espaço entre o `e` e `FrontIn`

2017-01-23 17:36 UTC, filipebarcos approved these changes

2017-02-03 19:13 UTC, merged

2017-02-03 19:13 UTC, filipebarcos commented
Parabéns @vitormalencar, sua palestra foi selecionada!